[general]
url  = "http://localhost:3666"

stylesheets = [ "main.css" ]
static_dir  = "share/static"

[templates]
dir    = "share/html_templates"
header = "header.mustache"
note   = "note.mustache"
front  = "frontpage.mustache"
list   = "list.mustache"
item   = "item.mustache"
