[general]
url = "http://localhost/"
stylesheets = [ "style.css" ]

[templates]
header = "share/header.mustache"
index  = "share/index.mustache"
listing = "share/listing.mustache"
text   = "share/text.mustache"
